/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5_progra_ii;

/**
 *
 * @author HP
 */
public class Circunferencia extends javax.swing.JFrame {

    /**
     * Creates new form Circunferencia
     */
    public Circunferencia() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        ejecutar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Ingrese el radio del circulo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 176, 23);

        dato.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        dato.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(dato);
        dato.setBounds(20, 120, 82, 29);

        ejecutar.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        ejecutar.setForeground(new java.awt.Color(0, 153, 255));
        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });
        getContentPane().add(ejecutar);
        ejecutar.setBounds(290, 70, 110, 31);

        resultado.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(resultado);
        resultado.setBounds(260, 150, 169, 29);

        limpiar.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        limpiar.setForeground(new java.awt.Color(0, 153, 255));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(10, 260, 110, 31);

        MenuPrincipal.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(0, 153, 255));
        MenuPrincipal.setText("Menu Guia1");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(MenuPrincipal);
        MenuPrincipal.setBounds(350, 260, 130, 31);

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("El resultado de la circunferencia es:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 120, 240, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMG-20180315-WA0061.jpg"))); // NOI18N
        jLabel2.setText("E");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-230, -60, 790, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
double Dato, circunferencia;
    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
      Dato = Double.parseDouble(dato.getText());
      
      circunferencia = 2 * 3.14 * Dato;
      
      resultado.setText("" +circunferencia);
    }//GEN-LAST:event_ejecutarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
       dato.setText("");
       resultado.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
       Guia01 G1=new Guia01();
     this.setVisible(false);
     G1.setVisible(true);
      G1.setLocationRelativeTo(null); 
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circunferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circunferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circunferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circunferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Circunferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPrincipal;
    private javax.swing.JTextField dato;
    private javax.swing.JButton ejecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
