/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5_progra_ii;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Esfera extends javax.swing.JFrame {

    /**
     * Creates new form Esfera
     */
    public Esfera() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoRadio = new javax.swing.JTextField();
        ejecutar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        MenuGUIA1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Ingrese el radio de la esfera");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 204, 20);

        campoRadio.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        campoRadio.setForeground(new java.awt.Color(0, 153, 255));
        campoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRadioActionPerformed(evt);
            }
        });
        getContentPane().add(campoRadio);
        campoRadio.setBounds(60, 80, 104, 26);

        ejecutar.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        ejecutar.setForeground(new java.awt.Color(0, 153, 255));
        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });
        getContentPane().add(ejecutar);
        ejecutar.setBounds(300, 40, 100, 29);

        resultado.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(resultado);
        resultado.setBounds(270, 120, 184, 26);

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("VOLUMEN DE UNA ESFERA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 10, 161, 20);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("EL resultado del volumen de la esfera es:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 90, 280, 23);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar);
        Limpiar.setBounds(20, 170, 80, 23);

        MenuGUIA1.setText("Menu GUIA1");
        MenuGUIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGUIA1ActionPerformed(evt);
            }
        });
        getContentPane().add(MenuGUIA1);
        MenuGUIA1.setBounds(400, 170, 110, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMG-20180315-WA0061.jpg"))); // NOI18N
        jLabel5.setText("imagen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-430, -140, 990, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
double radio, VolumenEsfera;
    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        radio = Double.parseDouble(campoRadio.getText());
        
        VolumenEsfera = (4/3) * 3.14 * (Math.pow(radio, 3));
        
        resultado.setText("" + VolumenEsfera);
    }//GEN-LAST:event_ejecutarActionPerformed

    private void campoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRadioActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        campoRadio.setText("");
        resultado.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void MenuGUIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGUIA1ActionPerformed
      Guia01 G1=new Guia01();
     this.setVisible(false);
     G1.setVisible(true);
      G1.setLocationRelativeTo(null); 
    }//GEN-LAST:event_MenuGUIA1ActionPerformed
     double vec[] = new double[10];
    double suma=0, promedio;
    void PedirDatos(){   
        for (int i = 0; i < 10; i++) {
            vec[i] = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor N." + (i+1)));       
    }    
        for (int i = 0; i < 10; i++) {
            suma = suma + vec[i];          
        }     
       promedio = suma/10;
       
       JOptionPane.showMessageDialog(null, "El promedio es: " + promedio);
       
        Guia01 o = new Guia01();
        o.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esfera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton MenuGUIA1;
    private javax.swing.JTextField campoRadio;
    private javax.swing.JButton ejecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
