/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5_progra_ii;

/**
 *
 * @author HP
 */
public class Guia01 extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public Guia01() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AreaDiagonal = new javax.swing.JButton();
        Circunferencia = new javax.swing.JButton();
        esfera = new javax.swing.JButton();
        cubo = new javax.swing.JButton();
        promedio = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        MenuP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("MENU GUIA1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 120, 22);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Calcular area o diagonal de una figura cuadrada");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 280, 22);

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Calcular circunferencia de un circulo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 214, 22);

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("calcular volumen de una esfera");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 181, 22);

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Calcular volumen de un cubo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 170, 22);

        jLabel6.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Calcular promedio de 10 numeros");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 260, 199, 22);

        AreaDiagonal.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        AreaDiagonal.setForeground(new java.awt.Color(0, 153, 255));
        AreaDiagonal.setText("ELEGIR");
        AreaDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaDiagonalActionPerformed(evt);
            }
        });
        getContentPane().add(AreaDiagonal);
        AreaDiagonal.setBounds(330, 80, 120, 31);

        Circunferencia.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        Circunferencia.setForeground(new java.awt.Color(0, 153, 255));
        Circunferencia.setText("ELEGIR");
        Circunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircunferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(Circunferencia);
        Circunferencia.setBounds(330, 130, 120, 31);

        esfera.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        esfera.setForeground(new java.awt.Color(0, 153, 255));
        esfera.setText("ELEGIR");
        esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esferaActionPerformed(evt);
            }
        });
        getContentPane().add(esfera);
        esfera.setBounds(330, 170, 120, 31);

        cubo.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        cubo.setForeground(new java.awt.Color(0, 153, 255));
        cubo.setText("ELEGIR");
        cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuboActionPerformed(evt);
            }
        });
        getContentPane().add(cubo);
        cubo.setBounds(330, 210, 120, 31);

        promedio.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        promedio.setForeground(new java.awt.Color(0, 153, 255));
        promedio.setText("ELEGIR");
        promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioActionPerformed(evt);
            }
        });
        getContentPane().add(promedio);
        promedio.setBounds(330, 260, 120, 31);

        Cerrar.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(0, 153, 255));
        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar);
        Cerrar.setBounds(30, 310, 100, 31);

        MenuP.setFont(new java.awt.Font("MV Boli", 0, 13)); // NOI18N
        MenuP.setForeground(new java.awt.Color(0, 153, 255));
        MenuP.setText("Regresar al Menu Principal");
        MenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPActionPerformed(evt);
            }
        });
        getContentPane().add(MenuP);
        MenuP.setBounds(260, 310, 250, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMG-20180315-WA0061.jpg"))); // NOI18N
        jLabel7.setText("imagen");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-410, -110, 1000, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaDiagonalActionPerformed
    AreaDiagonal a = new AreaDiagonal();
    this.setVisible(false);
    a.setVisible(true);
    a.setLocationRelativeTo(null);
    }//GEN-LAST:event_AreaDiagonalActionPerformed

    private void CircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircunferenciaActionPerformed
        Circunferencia b = new Circunferencia();
        this.setVisible(false);
    b.setVisible(true);
    b.setLocationRelativeTo(null);;
    }//GEN-LAST:event_CircunferenciaActionPerformed

    private void esferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esferaActionPerformed
       Esfera c =new Esfera();
       this.setVisible(false);
    c.setVisible(true);
    c.setLocationRelativeTo(null);
    }//GEN-LAST:event_esferaActionPerformed

    private void cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuboActionPerformed
        Cubo d = new Cubo();
        this.setVisible(false);
    d.setVisible(true);
    d.setLocationRelativeTo(null);
    }//GEN-LAST:event_cuboActionPerformed

    private void promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioActionPerformed
    Promedio e =new Promedio();
    this.setVisible(false);
    e.setVisible(true);
    e.setLocationRelativeTo(null);
    }//GEN-LAST:event_promedioActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
       dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void MenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPActionPerformed
        Menu_Principal ob=new Menu_Principal();
        this.setVisible(false);
        ob.setVisible(true);
        ob.setLocationRelativeTo(null);
    }//GEN-LAST:event_MenuPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AreaDiagonal;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Circunferencia;
    private javax.swing.JButton MenuP;
    private javax.swing.JButton cubo;
    private javax.swing.JButton esfera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton promedio;
    // End of variables declaration//GEN-END:variables
}
