
package guia5_progra_ii;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Judith
 */
public class Loing extends javax.swing.JFrame {

    /**
     * Creates new form Loing
     */
    public Loing() {
        initComponents();
         user.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        IniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));
        setSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        user.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(180, 180, 145, 32);

        pass.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(180, 240, 145, 32);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Usuario");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 170, 86, 33);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 240, 103, 33);

        Salir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(304, 11, 100, 27);

        IniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        IniciarSesion.setText("Iniciar Sesion");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesion);
        IniciarSesion.setBounds(180, 280, 140, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login-gov-600x314.png"))); // NOI18N
        jLabel3.setText("imagen");
        jLabel3.setAutoscrolls(true);
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -100, 450, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
      
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            IniciarSesionActionPerformed(null);
        }
    }//GEN-LAST:event_passKeyPressed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
String usere=user.getText();
String password= new String(pass.getText());
if(usere.equals(usuario) && password.equals(contraseña)){
  JOptionPane.showMessageDialog(null, "Bienvenido a tu menu de apss");
   Menu_Principal ventana = new Menu_Principal();
    this.setVisible(false);
    ventana.setVisible(true);
    ventana.setLocationRelativeTo(null);
  }else if (usere.equals(usuario) && password.isEmpty()){
    JOptionPane.showMessageDialog(null, "No has ingresado  la contraseña");    
  }else if(usere.isEmpty() && password.equals(contraseña)){
   JOptionPane.showMessageDialog(null, "No has ingresado el usuario");
  }else if(usere.compareTo(usuario)>0 && password.compareTo(contraseña)>0){
  JOptionPane.showMessageDialog(null, "Usuario erroneo y contraseña erronea"); 
  }else if(usere.equals(usuario) && password.compareTo(contraseña)>0){
  JOptionPane.showMessageDialog(null, "Usuario ingresado correctamente y contraseña erronea"); 
  }else if(usere.compareTo(usuario)>0 && password.equals(contraseña)){
  JOptionPane.showMessageDialog(null, "Usuario erroeneo y contraseña ingresada correctamente"); 
  }else if(usere.isEmpty() && password.isEmpty()){
   JOptionPane.showMessageDialog(null, "No has ingresado el usuario y la contraseña");
  }else if(usere.compareTo(usuario)<0 && password.compareTo(contraseña)<0){
  JOptionPane.showMessageDialog(null, "Usuario erroneo y contraseña erronea"); 
  }else if(usere.equals(usuario) && password.compareTo(contraseña)<0){
  JOptionPane.showMessageDialog(null, "Usuario ingresado correctamente y contraseña erronea"); 
  }else if(usere.compareTo(usuario)<0 && password.equals(contraseña)){
  JOptionPane.showMessageDialog(null, "Usuario erroeneo y contraseña ingresada correctamente");
  }   
      
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          pass.requestFocus();
        }
    }//GEN-LAST:event_userKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
 String usuario="ADMIN";
String contraseña="123ABC";

}
